# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "373349d948621559bd7e23797dfcaa57"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = false
name = "opt-order-edit"
handle = "opt-order-edit"

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,write_orders,customer_read_orders,customer_read_draft_orders,read_assigned_fulfillment_orders,write_assigned_fulfillment_orders,read_merchant_managed_fulfillment_orders,write_merchant_managed_fulfillment_orders,read_third_party_fulfillment_orders,write_third_party_fulfillment_orders,read_draft_orders,write_draft_orders,read_order_edits,write_order_edits,read_products,write_products"

[auth]
redirect_urls = [ "https://shopify.dev/apps/default-app-home/api/auth" ]

[pos]
embedded = false

[build]
dev_store_url = "shopninja-optimarko.myshopify.com"
include_config_on_deploy = true
