# Learn more about configuring your checkout UI extension:
# https://shopify.dev/api/checkout-extensions/checkout/configuration

# The version of APIs your extension will receive. Learn more:
# https://shopify.dev/docs/api/usage/versioning
api_version = "2024-10"

[[extensions]]
name = "Order Edit Checkout"
handle = "order-edit-checkout"
type = "ui_extension"


# Controls where in Shopify your extension will be injected,
# and the file that contains your extension’s source code. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/extension-targets-overview

[[extensions.targeting]]
module = "./src/Checkout.jsx"
target = "customer-account.order-status.block.render"
default_placement = "ORDER_STATUS1"

[extensions.capabilities]
api_access = true
block_progress = true
network_access = true


# Loads metafields on checkout resources, including the cart,
# products, customers, and more. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#metafields

# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_key"
# [[extensions.metafields]]
# namespace = "my_namespace"
# key = "my_other_key"

# Defines settings that will be collected from merchants installing
# your extension. Learn more:
# https://shopify.dev/docs/api/checkout-ui-extensions/unstable/configuration#settings-definition

# [extensions.settings]
# [[extensions.settings.fields]]
# key = "banner_title"
# type = "single_line_text_field"
# name = "Banner title"
# description = "Enter a title for the banner"

[extensions.settings]
[[extensions.settings.fields]]
key = "buttonText"
type = "single_line_text_field"
name = "Button Text"
description = "Enter a title for the button"

[[extensions.settings.fields]]
key = "buttonType"
type = "single_line_text_field"
name = "Button Type"
description = "The type of button that will be rendered. The visual presentation of the button type is controlled by merchants through the Branding API."

[[extensions.settings.fields.validations]]
name = "choices"
value = '["primary", "secondary", "plain"]'

[[extensions.settings.fields]]
key = "pageURL"
type = "single_line_text_field"
name = "Page Link"
description = "Enter the order edit page link. Eg. yourShop.myshopify.com/pages/order-edit"
